2175 - hide 'up to date' message when starting up

diff --git a/wart b/wart
--- a/wart
+++ b/wart
@@ -1,6 +1,10 @@
 #!/bin/sh
 
-make >&2 || exit 1
+# show commands if run
+# show nothing if not run
+make |grep -v "is up to date" >&2
+# hack: exit if commands failed
+make >&/dev/null || exit 1
 
 if command which rlwrap >/dev/null
 then
